##############################
- include_vars: "{{ ansible_os_family }}.yml"
  tags: always

- include: install_agent.yml
  tags: [install_agent]

##############################
- name: Test for Agent Provisioned
  stat: path=/var/alertlogic/etc/host_key.pem
  register: agent_provisioned
  ignore_errors: True
  tags: 
    - configure_al_agent
    - provision_al_agent

##############################
- include: configure_agent.yml
  tags: [configure_al_agent]

##############################
- include: provision_agent.yml
  tags: [provision_al_agent]

##############################
- include: configure_loggers.yml
  tags: [provision_al_agent]

##############################
- include: selinux.yml
  tags: [selinux]

