- win_stat: path='C:\Program Files (x86)\Common Files\AlertLogic\host_key.pem'
  register: al_agent_skip_provision

- set_fact: al_agent_windows_options="[]"

# SENSOR_HOST, SENSOR_PORT, USE_PROXY, PROV_NOW, PROV_KEY, PROV_ONLY, INSTALL_ONLY
- set_fact: al_agent_windows_options="{{al_agent_windows_options}} + [ \'INSTALL_ONLY=1\' ]"
  when: al_agent_skip_provision.stat.exists or al_agent_for_imaging

- set_fact: al_agent_windows_options="{{al_agent_windows_options}} + [ \'PROV_NOW=0\' ]"
  when: al_agent_skip_provision.stat.exists or al_agent_for_imaging

- set_fact: al_agent_windows_options="{{al_agent_windows_options}} + [ \'USE_PROXY=\' + al_agent_proxy_url ]"
  when: al_agent_proxy_url is defined and not al_agent_skip_provision.stat.exists and not al_agent_for_imaging

- set_fact: al_agent_windows_options="{{al_agent_windows_options}} + [ \'SENSOR_HOST=\' + al_agent_egress_host ]"
  when: al_agent_egress_host is defined and not al_agent_skip_provision.stat.exists and not al_agent_for_imaging

- set_fact: al_agent_windows_options="{{al_agent_windows_options}} + [ \'SENSOR_PORT=\' + al_agent_egress_port ]"
  when: al_agent_egress_port is defined and not al_agent_skip_provision.stat.exists and not al_agent_for_imaging

- set_fact: al_agent_windows_options="{{al_agent_windows_options}} + [ \'PROV_KEY=\' + al_agent_registration_key ]"
  when: not al_agent_skip_provision.stat.exists and al_agent_registration_key is defined and not al_agent_for_imaging

- set_fact: al_agent_windows="{{al_agent_windows_options|join(' ')}}"

- win_stat: path='C:/TEMP'
  register: al_agent_temp_dir

- win_file: path='C:/TEMP' state=directory
  when: not al_agent_temp_dir.stat.exists

- win_get_url: url='https://scc.alertlogic.net/software/al_agent-LATEST.msi' dest='C:/TEMP/al_agent-LATEST.msi' force=false

- debug: var=al_agent_windows

- name: Install AlertLogic Agent
  win_msi:
    path: 'C:\TEMP\al_agent-LATEST.msi'
    creates: 'C:\Program Files (x86)\AlertLogic'
    wait: True
    # Not working if more than one argument is passed, https://github.com/ansible/ansible-modules-core/issues/1229
    extra_args: "{{ al_agent_windows }}"
