##############################
- block:
    # Temporary workaround until ansible-modules-core PR #2613 is merged
  - include: deb-packages.yml
    when: ansible_os_family == "Debian"

  - name: Install AlertLogic Agent
    package: name="{{ al_agent_pkg_url }}" state=present
    tags: install_al_agent
    # Temporary workaround until ansible-modules-core PR #2613 is merged
    when: ansible_os_family != "Debian"

  - name: Start the AlertLogic Agent service
    service: name=al-agent state=started enabled=yes
    tags: install_al_agent
    when: not al_agent_for_imaging

