---
galaxy_info:
  author: Craig Davis 
  description: Configure and Install AlertLogic Agents
  company: AlertLogic
  license: Apache
  min_ansible_version: 2.0
  issue_tracker_url: https://github.com/alertlogic/al-agents-ansible-playbooks/issues
  platforms:
    - name: Debian
      versions:
        - squeeze
        - wheezy
    - name: EL
      versions:
        - 6
        - 7
    - name: Windows
      versions:
        - 2012R2
  categories:
    - monitoring
    - alertlogic
    - ids
  galaxy_tags:
    - monitoring
    - alertlogic
    - ids
dependencies: []
